name: spring_button
description: A simple widget for having interactable UI elements that respond to taps with a spring animation.
version: 1.0.4
author: Ali Yigit Bireroglu <aliyigitbireroglu@gmail.com>
repository: https://github.com/aliyigitbireroglu/flutter-spring-button
homepage: https://www.cosmossoftware.coffee

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
